import type { AppLocale } from './locales'

export const privacySlugs = ['scope', 'data-collected', 'processing-purpose', 'user-rights', 'edit-delete', 'security-storage', 'sync-data', 'data-sharing', 'cross-border', 'cookies', 'data-incidents', 'user-obligations', 'policy-changes', 'contact'] as const
type Section = [title: string, ...paragraphs: string[]]
type PrivacyCopy = { title: string; introTitle: string; toc: string; intro: string[]; sections: Section[]; contact: string; terms: string }

// Product-specific policy text supplied by the owner, rewritten for AezCheck.
// Topic order verified against https://nolimitadsmanager.com/vi/privacy.
export const privacyCopy: Record<AppLocale, PrivacyCopy> = {
  vi: {
    title: 'Chính sách bảo mật AezCheck', introTitle: 'Giới thiệu', toc: 'Nội dung trang', contact: 'Liên hệ AezCheck', terms: 'Điều khoản dịch vụ',
    intro: [
      'AezCheck (“AezCheck”, “chúng tôi”) vận hành nền tảng AezCheck và các sản phẩm, dịch vụ liên quan.',
      'Chính sách này giải thích cách AezCheck thu thập, sử dụng, lưu trữ, chia sẻ và bảo vệ dữ liệu cá nhân của người dùng khi truy cập website hoặc sử dụng nền tảng AezCheck.',
      'Bằng việc đăng ký tài khoản, kết nối dữ liệu hoặc tiếp tục sử dụng dịch vụ, bạn xác nhận đã đọc và hiểu Chính sách này.',
    ],
    sections: [
      ['Phạm vi áp dụng', 'Chính sách áp dụng khi bạn truy cập website, đăng ký tài khoản, tạo hoặc tham gia workspace AezCheck, kết nối VIA, BM, TKQC, Page, hoặc sử dụng các chức năng quản lý, giám sát, báo cáo, tài chính, cảnh báo, phân quyền, audit log và Shield. Việc tiếp tục sử dụng dịch vụ được hiểu là bạn đã đọc và hiểu Chính sách.'],
      ['Thông tin được thu thập',
        'A. Thông tin tài khoản — Họ tên, email, số điện thoại nếu có, tên workspace, vai trò, quyền hạn và thông tin định danh tài khoản.',
        'B. Thông tin kỹ thuật — Địa chỉ IP, thiết bị, hệ điều hành, trình duyệt, thời gian truy cập, phiên đăng nhập, log, cookies và dữ liệu phục vụ bảo mật.',
        'C. Thông tin sử dụng dịch vụ — Lịch sử thao tác, cấu hình workspace, trạng thái kết nối, nhật ký hoạt động, tín hiệu rủi ro và dữ liệu phát sinh khi sử dụng các tính năng.',
        'D. Dữ liệu đồng bộ — Token, session, cấu hình kỹ thuật và dữ liệu cần thiết để đồng bộ tài sản hoặc trạng thái khi bạn chủ động kết nối.',
        'E. Thông tin hỗ trợ — Nội dung trao đổi, phản hồi, yêu cầu hoặc ticket hỗ trợ, cùng tệp và hình ảnh bạn gửi cho AezCheck.'],
      ['Mục đích xử lý dữ liệu', 'AezCheck xử lý dữ liệu để tạo và xác thực tài khoản; quản lý workspace; cung cấp, duy trì dịch vụ và đồng bộ tài sản; hiển thị báo cáo, dashboard; phát hiện lỗi, rủi ro và gửi cảnh báo. Dữ liệu còn phục vụ Shield / Tường lửa bảo vệ và giám sát, hỗ trợ khách hàng, bảo mật hệ thống, phân tích và cải thiện sản phẩm, gửi thông báo kỹ thuật hoặc thay đổi chính sách, cũng như thực hiện nghĩa vụ pháp lý.', 'AezCheck không sử dụng dữ liệu cá nhân cho mục đích trái pháp luật hoặc ngoài phạm vi đã thông báo, trừ khi có cơ sở pháp lý phù hợp hoặc được người dùng đồng ý.'],
      ['Sự đồng ý và quyền của người dùng', 'Theo pháp luật áp dụng, bạn có thể có quyền truy cập, chỉnh sửa, yêu cầu cung cấp hoặc xóa dữ liệu; hạn chế, phản đối xử lý; và rút lại sự đồng ý khi phù hợp. Việc rút lại sự đồng ý hoặc yêu cầu xóa có thể ảnh hưởng đến khả năng sử dụng một số tính năng.', 'Các yêu cầu liên quan đến dữ liệu cá nhân có thể được gửi qua trang Liên hệ của AezCheck.'],
      ['Chỉnh sửa và xoá thông tin', 'Bạn có thể tự cập nhật một số thông tin trong tài khoản. Thay đổi thông tin nhạy cảm, xóa tài khoản hoặc xóa workspace có thể cần xác minh để bảo vệ dữ liệu và người có quyền truy cập.', 'Một số dữ liệu có thể tiếp tục được lưu giữ khi cần tuân thủ pháp luật, xử lý tranh chấp, phòng chống gian lận, bảo đảm an toàn hệ thống hoặc bảo vệ quyền lợi hợp pháp.'],
      ['Bảo mật và lưu trữ dữ liệu', 'AezCheck áp dụng các biện pháp kỹ thuật và quản trị phù hợp như kiểm soát truy cập, phân quyền, mã hóa phù hợp, ghi nhận nhật ký hoạt động, theo dõi rủi ro, sao lưu, giám sát bảo mật và bảo vệ hạ tầng.', 'Dữ liệu được giữ trong thời gian cần để cung cấp dịch vụ hoặc đáp ứng yêu cầu pháp luật, vận hành, giải quyết tranh chấp và bảo mật. Khi không còn cần thiết, dữ liệu có thể được xóa, ẩn danh hoặc hạn chế truy cập và lưu trữ.'],
      ['Dữ liệu đồng bộ của AezCheck', 'Khi bạn chủ động kết nối hoặc bật đồng bộ, AezCheck có thể xử lý và lưu trữ dữ liệu kỹ thuật cần thiết để đồng bộ tài sản, cập nhật trạng thái, phục vụ cảnh báo, giám sát và hỗ trợ vận hành. Dữ liệu nhạy cảm được xử lý với các biện pháp bảo mật phù hợp.', 'Cách thức mã hóa, lưu trữ và quản lý dữ liệu đồng bộ phụ thuộc vào loại kết nối và cơ chế kỹ thuật tương ứng của AezCheck.'],
      ['Chia sẻ dữ liệu', 'AezCheck không bán dữ liệu cá nhân của người dùng.', 'Trong phạm vi cần thiết, dữ liệu có thể được chia sẻ với nhà cung cấp hạ tầng, cloud và lưu trữ, bảo mật, hỗ trợ vận hành, chăm sóc khách hàng, đối tác kỹ thuật, bên xử lý dữ liệu được chỉ định hoặc cơ quan có thẩm quyền khi có yêu cầu hợp pháp. Bên nhận dữ liệu phải tuân thủ nghĩa vụ bảo mật phù hợp và chỉ xử lý theo mục đích được phép.'],
      ['Lưu trữ và chuyển dữ liệu ra nước ngoài', 'Tùy hạ tầng phục vụ dịch vụ, dữ liệu có thể được lưu trữ hoặc xử lý tại Việt Nam hay nước ngoài. Nếu phát sinh chuyển dữ liệu xuyên biên giới, AezCheck thực hiện các nghĩa vụ phù hợp theo pháp luật Việt Nam và quy định áp dụng.'],
      ['Cookies', 'AezCheck có thể dùng cookies hoặc công nghệ tương tự để duy trì phiên đăng nhập, ghi nhớ tùy chọn, bảo mật tài khoản, phân tích hiệu suất, cải thiện trải nghiệm và phát hiện rủi ro. Bạn có thể điều chỉnh việc sử dụng cookies trong trình duyệt; tắt cookies có thể ảnh hưởng một số tính năng.'],
      ['Sự cố dữ liệu', 'Khi phát hiện sự cố dữ liệu có nguy cơ ảnh hưởng đến người dùng, AezCheck sẽ thực hiện các biện pháp cần thiết để ngăn chặn, khắc phục và giảm thiểu thiệt hại. Khi pháp luật yêu cầu, AezCheck thực hiện nghĩa vụ thông báo phù hợp cho cơ quan có thẩm quyền, người dùng hoặc bên liên quan.'],
      ['Nghĩa vụ của người dùng', 'Bạn có trách nhiệm cung cấp thông tin chính xác; bảo vệ tài khoản, mật khẩu, thiết bị, token, cookie và quyền truy cập; không chia sẻ thông tin xác thực với người không có thẩm quyền; không dùng dịch vụ trái pháp luật; và thông báo sớm cho AezCheck khi phát hiện rủi ro bảo mật.'],
      ['Thay đổi Chính sách', 'AezCheck có thể cập nhật Chính sách khi sản phẩm, dịch vụ, yêu cầu kỹ thuật hoặc quy định pháp luật thay đổi. Các thay đổi quan trọng sẽ được thông báo qua website, trong hệ thống, email hoặc phương thức phù hợp khác.'],
      ['Thông tin liên hệ', 'Mọi câu hỏi, yêu cầu hoặc khiếu nại liên quan đến dữ liệu cá nhân và Chính sách bảo mật vui lòng liên hệ AezCheck thông qua trang Liên hệ.'],
    ],
  },
  en: {
    title: 'AezCheck Privacy Policy', introTitle: 'Introduction', toc: 'On this page', contact: 'Contact AezCheck', terms: 'Terms of service',
    intro: ['AezCheck (“AezCheck”, “we”) operates the AezCheck platform and related products and services.', 'This Policy explains how AezCheck collects, uses, stores, shares and protects personal data when you visit the website or use the platform.', 'By registering an account, connecting data or continuing to use the service, you acknowledge that you have read and understood this Policy.'],
    sections: [
      ['Scope', 'This Policy applies when you visit the website, register an account, create or join an AezCheck workspace, connect VIA, BM, ad accounts or Pages, or use management, monitoring, reporting, finance, alerts, permissions, audit logs and Shield features. Continued use indicates that you have read and understood this Policy.'],
      ['Information collected', 'A. Account information — Name, email, phone number if provided, workspace name, roles, permissions and account identifiers.', 'B. Technical information — IP address, device, operating system, browser, access times, login sessions, logs, cookies and security data.', 'C. Service usage information — Action history, workspace settings, connection status, activity logs, risk signals and data generated through features.', 'D. Synchronized data — Tokens, sessions, technical configuration and data required to synchronize assets or status when you actively connect them.', 'E. Support information — Conversations, feedback, support requests or tickets, and files or images you send to AezCheck.'],
      ['Purposes of processing', 'AezCheck processes data to create and authenticate accounts, administer workspaces, provide and maintain services, synchronize assets, display reports and dashboards, detect errors and risks, and send alerts. Processing also supports Shield / Firewall protection and monitoring, customer assistance, system security, product analytics and improvements, technical or policy notices, and legal obligations.', 'AezCheck does not use personal data for unlawful purposes or beyond the notified scope unless there is an appropriate legal basis or user consent.'],
      ['Consent and user rights', 'Depending on applicable law, you may have rights to access, correct, obtain or delete data, restrict or object to processing, and withdraw consent where appropriate. Withdrawal of consent or a deletion request may affect access to some features.', 'Personal data requests can be submitted through the AezCheck Contact page.'],
      ['Editing and deleting information', 'You can update certain information in your account. Changes to sensitive information, account deletion or workspace deletion may require verification to protect data and authorized users.', 'Some data may be retained where necessary for legal compliance, dispute resolution, fraud prevention, system safety or protection of legitimate interests.'],
      ['Data security and retention', 'AezCheck applies appropriate technical and organizational measures such as access controls, permissions, suitable encryption, activity logs, risk monitoring, backups, security monitoring and infrastructure protection.', 'Data is retained for as long as needed to provide services or meet legal, operational, dispute-resolution and security requirements. When no longer needed, it may be deleted, anonymized or placed under restricted access and storage.'],
      ['AezCheck synchronized data', 'When you actively connect data or enable synchronization, AezCheck may process and store technical data needed to synchronize assets, update status, support alerts and monitoring, and assist operations. Sensitive data is handled using appropriate security measures.', 'Encryption, storage and management of synchronized data depend on the connection type and the corresponding AezCheck technical mechanisms.'],
      ['Data sharing', 'AezCheck does not sell users’ personal data.', 'Data may be shared only as necessary with infrastructure, cloud and storage, security, operational support and customer service providers, technical partners, appointed processors or competent authorities acting on lawful requests. Recipients must follow appropriate confidentiality obligations and process data only for authorized purposes.'],
      ['International storage and transfers', 'Depending on the service infrastructure, data may be stored or processed in Vietnam or abroad. Where cross-border transfers occur, AezCheck fulfills the relevant obligations under Vietnamese law and applicable regulations.'],
      ['Cookies', 'AezCheck may use cookies or similar technologies to maintain login sessions, remember preferences, secure accounts, analyze performance, improve experience and detect risks. You can adjust cookie settings in your browser; disabling cookies may affect some features.'],
      ['Data incidents', 'When a data incident that may affect users is detected, AezCheck will take necessary steps to contain, remedy and mitigate harm. Where required by law, AezCheck will fulfill appropriate notification obligations to competent authorities, users or relevant parties.'],
      ['User obligations', 'You must provide accurate information; protect your account, password, devices, tokens, cookies and access rights; avoid sharing credentials with unauthorized people; refrain from unlawful use; and promptly notify AezCheck of detected security risks.'],
      ['Policy changes', 'AezCheck may update this Policy as products, services, technical requirements or laws change. Material changes will be communicated through the website, in-product notices, email or another appropriate method.'],
      ['Contact information', 'Please contact AezCheck through the Contact page with any questions, requests or complaints concerning personal data or this Privacy Policy.'],
    ],
  },
}
