export type FeatureId = 'workspace' | 'core' | 'finance' | 'monitoring' | 'reports'
export type FeatureCopy = { id: FeatureId; title: string; kicker: string; headline: string; description: string; details: string[]; cta: string; href: string }

export const spotlightCopy: Record<'vi' | 'en', FeatureCopy[]> = {
  vi: [
    { id: 'workspace', title: 'Agency Workspace', kicker: 'Lợi ích:', headline: 'Tất cả trong một nơi. Vận hành dễ dàng hơn.', description: 'Agency Workspace là không gian làm việc tập trung cho toàn bộ quy trình cho thuê tài khoản quảng cáo, giúp bạn tổ chức nhóm, quản lý nhân sự, khách hàng, tài khoản quảng cáo cho thuê và theo dõi chi tiêu — tất cả trong một nền tảng duy nhất.', details: ['Nhóm, Nhân sự, Khách hàng, TKQC cho thuê, Chi tiêu TKQC.'], cta: 'Dùng thử miễn phí', href: '#contact' },
    { id: 'core', title: 'Cụm tính năng quản lý cốt lõi', kicker: 'QUẢN LÝ TÀI SẢN & QUẢNG CÁO', headline: 'Tập trung tài sản quảng cáo vào một nơi', description: 'Quản lý các tài sản Facebook và theo dõi các tài khoản quảng cáo trên cùng hệ thống.', details: ['Via, Tài khoản quảng cáo, BM và Fanpage', 'Theo dõi trạng thái, token và thông tin liên quan', 'Tra cứu, lọc, tùy chỉnh cột và xuất dữ liệu'], cta: 'Xem tính năng cốt lõi', href: '#asset-management' },
    { id: 'finance', title: 'Cụm tính năng quản lý tài chính', kicker: 'DÒNG TIỀN KHÁCH THUÊ', headline: 'Kiểm soát tiền nạp, phí và công nợ', description: 'Theo dõi các chỉ số tài chính gắn trực tiếp với khách hàng và TKQC cho thuê mà không tách khỏi luồng vận hành.', details: ['Tổng tiền nạp và số dư hạn mức khách hàng', 'Loại thu phí, giá và tổng phí thuê', 'Chi tiêu, công nợ và quyết toán TKQC'], cta: 'Xem quản lý tài chính', href: '#finance' },
    { id: 'monitoring', title: 'Giám sát & an toàn vận hành', kicker: 'TRẠNG THÁI & RỦI RO', headline: 'Nhìn thấy vấn đề trước khi vận hành bị gián đoạn', description: 'Tập trung các trạng thái quan trọng của tài sản để người vận hành nhận biết nhanh các tài khoản cần chú ý.', details: ['Trạng thái Via và quyền chạy quảng cáo', '2FA, token và thời điểm token hết hạn', 'Trạng thái TKQC và các tài sản liên quan'], cta: 'Xem giám sát vận hành', href: '#shield' },
    { id: 'reports', title: 'Cụm tính năng báo cáo & phân tích', kicker: 'CHI TIÊU & ĐỐI SOÁT', headline: 'Biến dữ liệu vận hành thành số liệu dễ kiểm tra', description: 'Theo dõi chi tiêu theo ngày, so sánh số liệu và xuất dữ liệu để phục vụ việc kiểm tra, đối soát và báo cáo.', details: ['Chi tiêu TKQC theo ngày trong tháng', 'Đối chiếu số liệu Auto và CS', 'Lọc theo tiêu chí và xuất dữ liệu'], cta: 'Xem báo cáo & phân tích', href: '#control-center' },
  ],
  en: [
    { id: 'workspace', title: 'Agency Workspace', kicker: 'Benefits:', headline: 'Everything in one place. Easier operations.', description: 'Agency Workspace brings your entire ad account rental workflow together. Organize teams, manage staff, clients and rented ad accounts, and track spend — all in a single platform.', details: ['Teams, Staff, Clients, Rented TKQC, TKQC spend.'], cta: 'Try for free', href: '#contact' },
    { id: 'core', title: 'Core management features', kicker: 'ASSETS & ADVERTISING', headline: 'Bring advertising assets into one place', description: 'Manage Facebook assets and monitor ad accounts in the same system.', details: ['VIA, ad accounts, BM and Fanpage', 'Monitor status, tokens and related information', 'Search, filter, customize columns and export data'], cta: 'Explore core features', href: '#asset-management' },
    { id: 'finance', title: 'Financial management', kicker: 'RENTAL CLIENT CASH FLOW', headline: 'Control deposits, fees and balances due', description: 'Track financial figures tied directly to clients and rented TKQC without leaving your operational workflow.', details: ['Total deposits and remaining client limits', 'Fee types, rates and total rental fees', 'Spend, balances due and TKQC settlement'], cta: 'Explore financial management', href: '#finance' },
    { id: 'monitoring', title: 'Monitoring & operational safety', kicker: 'STATUS & RISK', headline: 'See issues before operations are interrupted', description: 'Bring important asset statuses together so operators can quickly identify accounts that need attention.', details: ['VIA status and advertising permissions', '2FA, tokens and token expiration', 'TKQC status and related assets'], cta: 'Explore monitoring', href: '#shield' },
    { id: 'reports', title: 'Reporting & analytics', kicker: 'SPEND & RECONCILIATION', headline: 'Turn operational data into figures you can check', description: 'Track daily spend, compare figures and export data for checking, reconciliation and reporting.', details: ['Daily TKQC spend throughout the month', 'Compare Auto and CS figures', 'Filter by criteria and export data'], cta: 'Explore reporting & analytics', href: '#control-center' },
  ],
}
