import fs from 'node:fs'
import assert from 'node:assert/strict'

const targets = await (await fetch('http://localhost:9338/json')).json()
const target = targets.find(t => t.type === 'page')
const socket = new WebSocket(target.webSocketDebuggerUrl)
await new Promise(resolve => socket.addEventListener('open',resolve,{once:true}))
let sequence=0; const pending=new Map(), errors=[]
socket.addEventListener('message',event=>{
  const message=JSON.parse(event.data)
  if(message.id){const request=pending.get(message.id);pending.delete(message.id);message.error?request.reject(message.error):request.resolve(message.result)}
  if(message.method==='Runtime.exceptionThrown')errors.push(message.params.exceptionDetails)
})
const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++sequence;pending.set(id,{resolve,reject});socket.send(JSON.stringify({id,method,params}))})
const evaluate=async expression=>{const result=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(result.exceptionDetails)throw Error(JSON.stringify(result.exceptionDetails));return result.result.value}
const pause=ms=>new Promise(r=>setTimeout(r,ms))
const check=async(expression,label)=>assert.ok(await evaluate(expression),label)
await send('Page.enable');await send('Runtime.enable')
await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]})
await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false})
await send('Page.navigate',{url:'http://localhost:8443/vi/guide'})
await pause(1200)
await check(`document.querySelectorAll('.guide-module').length===16`,'16 source modules')
await check(`document.querySelectorAll('.guide-module h3').length===62`,'62 subsections')
await check(`document.querySelectorAll('.guide-tip').length===26`,'26 tips')
await check(`document.querySelectorAll('.guide-figure figcaption').length===15`,'15 captions')
await check(`document.querySelectorAll('.guide-steps > li').length===20`,'20 ordered steps')
await check(`document.querySelectorAll('.guide-list li, .guide-steps ul li').length===345`,'345 bullets including nested bullets')
await check(`document.querySelectorAll('.az-navbar').length===1 && !document.querySelector('.az-navbar [aria-current]')`,'single shared neutral header')
await check(`document.querySelectorAll('.guide-toc-group').length===13`,'13 TOC groups')
await check(`document.querySelectorAll('.guide-figure img[loading="lazy"][decoding="async"]').length===31`,'lazy screenshots')
await check(`new Set([...document.querySelectorAll('.guide-figure img')].map(i=>i.src)).size===20`,'20 unique screenshots')
const assets=JSON.parse(fs.readFileSync('docs/guide/asset-manifest.json','utf8')).assets
for(const asset of assets){await check(`new Promise(resolve=>{const image=new Image();image.onload=()=>resolve(image.naturalWidth===${asset.width}&&image.naturalHeight===${asset.height});image.onerror=()=>resolve(false);image.src=${JSON.stringify(asset.url)}})`,`runtime image ${asset.file}`)}
// Search uses actual input events so React's controlled input is exercised.
await evaluate(`(()=>{const input=document.querySelector('.guide-search input');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,'token');input.dispatchEvent(new Event('input',{bubbles:true}))})()`)
await pause(80)
await check(`document.querySelectorAll('.guide-toc-group').length===0 && !!document.querySelector('.guide-no-results')`,'empty title search')
await evaluate(`(()=>{const input=document.querySelector('.guide-search input');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,'phan quyen');input.dispatchEvent(new Event('input',{bubbles:true}))})()`)
await pause(80)
await check(`document.querySelectorAll('.guide-toc-group').length>0 && document.querySelectorAll('.guide-toc-group').length<13`,'accent-insensitive title search')
await evaluate(`(()=>{const input=document.querySelector('.guide-search input');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,'');input.dispatchEvent(new Event('input',{bubbles:true}))})()`)
await pause(80)
await evaluate(`document.querySelector('.guide-figure img').focus();document.querySelector('.guide-figure img').click()`)
await pause(100)
await check(`!!document.querySelector('.guide-lightbox[open]') && document.body.style.overflow==='hidden'`,'lightbox opens and locks background')
await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape',windowsVirtualKeyCode:27})
await send('Input.dispatchKeyEvent',{type:'keyUp',key:'Escape',code:'Escape',windowsVirtualKeyCode:27})
await pause(80)
await check(`!document.querySelector('.guide-lightbox') && document.activeElement.matches('.guide-figure img')`,'escape closes and restores focus')
await evaluate(`document.querySelector('.guide-figure img').click()`);await pause(50)
await evaluate(`document.querySelector('.guide-lightbox').click()`);await pause(50)
await check(`!document.querySelector('.guide-lightbox')`,'outside click closes')
await evaluate(`document.querySelector('.guide-figure img').click()`);await pause(50)
await evaluate(`document.querySelector('.guide-lightbox-close').click()`);await pause(50)
await check(`!document.querySelector('.guide-lightbox')`,'close button works')
await send('Page.navigate',{url:'http://localhost:8443/vi/guide#permissions-cap-va-thu-hoi-quyen'})
await pause(700)
await check(`(()=>{const h=document.getElementById('permissions-cap-va-thu-hoi-quyen');return h.getBoundingClientRect().top>=90&&h.getBoundingClientRect().top<165})()`,'deep link clears sticky header')
await send('Page.reload');await pause(900)
await check(`(()=>{const h=document.getElementById('permissions-cap-va-thu-hoi-quyen');return h.getBoundingClientRect().top>=90&&h.getBoundingClientRect().top<165})()`,'reload deep link')
await check(`document.querySelector('.guide-toc a[aria-current]').hash.endsWith('permissions-cap-va-thu-hoi-quyen')`,'scroll spy active subsection')
await evaluate(`document.querySelector('.az-language-button').click()`);await pause(50)
await evaluate(`document.querySelector('.az-language-menu [lang="en"]').click()`);await pause(80)
await check(`location.pathname==='/en/guide' && document.documentElement.lang==='en' && document.querySelector('.guide-page').lang==='en' && !document.querySelector('.az-navbar [aria-current]')`,'locale stays on guide; English guide')
await evaluate(`document.querySelector('.az-language-button').click()`);await pause(50)
await evaluate(`document.querySelector('.az-language-menu [lang="vi"]').click()`);await pause(50)
fs.mkdirSync('artifacts/guide-ui',{recursive:true})
const responsive=[]
for(const [width,height] of [[1440,1000],[1024,900],[768,1024],[390,844]]){
  await send('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:false})
  await send('Page.navigate',{url:'http://localhost:8443/vi/guide'});await pause(700)
  const layout=await evaluate(`({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,tocOpen:document.querySelector('.guide-toc').open,imagesFit:[...document.querySelectorAll('.guide-figure img')].every(i=>i.getBoundingClientRect().right<=innerWidth),sidebar:getComputedStyle(document.querySelector('.guide-sidebar')).position})`)
  assert.ok(layout.scrollWidth<=width,`overflow at ${width}`);assert.ok(layout.imagesFit,`images fit at ${width}`)
  assert.equal(layout.tocOpen,width>=960,`TOC responsive ${width}`)
  const screenshot=await send('Page.captureScreenshot',{format:'png'})
  fs.writeFileSync(`artifacts/guide-ui/guide-${width}.png`,Buffer.from(screenshot.data,'base64'))
  responsive.push(layout)
}
await evaluate(`document.querySelector('.guide-toc summary').click()`);await pause(80)
await check(`document.querySelector('.guide-toc').open`,'mobile TOC opens')
await evaluate(`document.querySelector('.guide-toc a[href="/vi/guide#shield"]').click()`);await pause(400)
await check(`!document.querySelector('.guide-toc').open && document.getElementById('shield').getBoundingClientRect().top>=90 && document.getElementById('shield').getBoundingClientRect().top<165`,'mobile TOC navigation')
await evaluate(`document.querySelector('#mobile-menu-toggle').click()`);await pause(100)
await check(`document.querySelector('#mobile-menu-toggle').getAttribute('aria-expanded')==='true'`,'shared mobile menu opens')
await evaluate(`document.querySelector('#mobile-navigation a[href="/vi/pricing"]').click()`);await pause(400)
await check(`location.pathname==='/vi/pricing' && !!document.querySelector('.az-navbar [aria-current="page"]')`,'pricing still active')
await send('Page.navigate',{url:'http://localhost:8443/vi/guide'});await pause(500)
await evaluate(`document.querySelector('.az-navbar-brand').click()`);await pause(400)
await check(`!!document.getElementById('hero') && !document.querySelector('.guide-page')`,'logo returns to landing')
await evaluate(`document.querySelector('footer a[href$="/guide"]').click()`);await pause(500)
await check(`!!document.querySelector('.guide-page') && !document.querySelector('.az-navbar [aria-current]')`,'footer opens Guide')
assert.equal(errors.length,0,'no runtime exceptions')
const report={result:'PASS',responsive,images:assets.length,groups:13,subsections:62,tips:26,captions:15,steps:20,bullets:345,errors}
fs.writeFileSync('docs/guide/browser-qa.json',JSON.stringify(report,null,2))
console.log(JSON.stringify(report,null,2));socket.close()
